#!/usr/bin/env python3
"""
Generate a standard REDLog3G10 / REDWideGamutRGB → Rec.709 3D LUT (.cube format).

The transform chain:
  1. Decode REDLog3G10 → scene-linear
  2. REDWideGamutRGB → Rec.709 color matrix
  3. Apply Rec.709 OETF (display gamma)

Output: 33-point 3D LUT in .cube format.
"""

import math
import sys
from pathlib import Path

LUT_SIZE = 33


def red_log3g10_to_linear(x):
    """Decode REDLog3G10 encoded value to scene-linear."""
    # RED's Log3G10 encoding: y = A + B * log10(C * x + 1)
    # A = 0.091, B = 0.6, C = 155.975327
    # Inverse: x = (10^((y - A) / B) - 1) / C
    A = 0.091
    B = 0.6
    C = 155.975327
    if x <= A:
        # Below the log curve — extrapolate linearly through origin
        return (x - A) / (B * C * math.log10(math.e))
    return (10.0 ** ((x - A) / B) - 1.0) / C


def rec709_oetf(L):
    """Rec.709 OETF: scene-linear → display signal."""
    if L < 0.018:
        return max(0.0, 4.5 * L)
    return min(1.0, 1.099 * (max(0.0, L) ** 0.45) - 0.099)


# REDWideGamutRGB to Rec.709 (sRGB primaries) 3x3 matrix
# Source: RED technical documentation
RWG_TO_709 = [
    [1.4183, -0.3209, -0.0974],
    [-0.0913, 1.1673, -0.0760],
    [-0.0094, -0.0560, 1.0654],
]


def matrix_mult(m, rgb):
    return [
        m[0][0] * rgb[0] + m[0][1] * rgb[1] + m[0][2] * rgb[2],
        m[1][0] * rgb[0] + m[1][1] * rgb[1] + m[1][2] * rgb[2],
        m[2][0] * rgb[0] + m[2][1] * rgb[1] + m[2][2] * rgb[2],
    ]


def transform(r_in, g_in, b_in):
    """Full transform: Log3G10/RWG input → Rec.709 display output."""
    # Step 1: Decode log to linear
    r_lin = red_log3g10_to_linear(r_in)
    g_lin = red_log3g10_to_linear(g_in)
    b_lin = red_log3g10_to_linear(b_in)

    # Step 2: Color matrix (RWG → 709)
    r_709, g_709, b_709 = matrix_mult(RWG_TO_709, [r_lin, g_lin, b_lin])

    # Step 3: Rec.709 OETF
    return rec709_oetf(r_709), rec709_oetf(g_709), rec709_oetf(b_709)


def main():
    out_path = Path(__file__).parent.parent / "config" / "luts" / "REDLog3G10_RWG_to_Rec709.cube"

    with open(out_path, "w") as f:
        f.write("# REDLog3G10 / REDWideGamutRGB → Rec.709\n")
        f.write(f"# Generated by spheris-smart-stitch/tools/generate_lut.py\n")
        f.write(f"TITLE \"REDLog3G10 RWG to Rec.709\"\n")
        f.write(f"LUT_3D_SIZE {LUT_SIZE}\n")
        f.write(f"DOMAIN_MIN 0.0 0.0 0.0\n")
        f.write(f"DOMAIN_MAX 1.0 1.0 1.0\n")
        f.write("\n")

        for b_i in range(LUT_SIZE):
            for g_i in range(LUT_SIZE):
                for r_i in range(LUT_SIZE):
                    r_in = r_i / (LUT_SIZE - 1)
                    g_in = g_i / (LUT_SIZE - 1)
                    b_in = b_i / (LUT_SIZE - 1)
                    r_out, g_out, b_out = transform(r_in, g_in, b_in)
                    f.write(f"{r_out:.6f} {g_out:.6f} {b_out:.6f}\n")

    print(f"Generated {LUT_SIZE}x{LUT_SIZE}x{LUT_SIZE} LUT → {out_path}")
    print(f"  {LUT_SIZE ** 3} entries, {out_path.stat().st_size / 1024:.0f} KB")


if __name__ == "__main__":
    main()
